language: node_js
node_js:
  - "lts/*"
  - "node"

stages:
  - name: deploy
    if: branch = master

jobs:
  include:
    - stage: deploy
      deploy:
        provider: npm
        api_key: $NPM_API_KEY
        email: $NPM_MAIL
